// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_yoWxOXsW8OCxfUUmtf-c7eaJRAe3800',
    appId: '1:829865412144:web:adeaa3bddde63604ab0ff5',
    messagingSenderId: '829865412144',
    projectId: 'archivageucb',
    authDomain: 'archivageucb.firebaseapp.com',
    storageBucket: 'archivageucb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBghKBLyXQgG2vtkaZkJxVdE4jhFJnxveg',
    appId: '1:829865412144:android:6bcd557c39692593ab0ff5',
    messagingSenderId: '829865412144',
    projectId: 'archivageucb',
    storageBucket: 'archivageucb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1fGbCAJcIbZWS3Fwpoz3yfUQAv-ORN-o',
    appId: '1:829865412144:ios:1d428f08cf4d5a36ab0ff5',
    messagingSenderId: '829865412144',
    projectId: 'archivageucb',
    storageBucket: 'archivageucb.firebasestorage.app',
    iosBundleId: 'com.domaine.archivageucb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1fGbCAJcIbZWS3Fwpoz3yfUQAv-ORN-o',
    appId: '1:829865412144:ios:1d428f08cf4d5a36ab0ff5',
    messagingSenderId: '829865412144',
    projectId: 'archivageucb',
    storageBucket: 'archivageucb.firebasestorage.app',
    iosBundleId: 'com.domaine.archivageucb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_yoWxOXsW8OCxfUUmtf-c7eaJRAe3800',
    appId: '1:829865412144:web:9a8fb6141c3aa2e0ab0ff5',
    messagingSenderId: '829865412144',
    projectId: 'archivageucb',
    authDomain: 'archivageucb.firebaseapp.com',
    storageBucket: 'archivageucb.firebasestorage.app',
  );
}
